# Website settings
baseurl: "/"
url: "https://www.gruntwork.io"
name: "Gruntwork | DevOps as a Service"
description: "Your entire infrastructure. Defined as code. In about a day. At Gruntwork, we get you up and running on AWS with Terraform and you get 100% of the code."
full_company_name: "Gruntwork, Inc"
thumbnail_path: "/assets/img/gruntwork-logo/gruntwork-overview.png"
repository: "gruntwork-io/gruntwork-io.github.io"

highlighter: rouge
timezone: 'America/Los_Angeles'

assets_base_url: '/assets/'
ga_tracker: UA-76462621-1

exclude:
 - .dockerignore
 - .editorconfig
 - .gitignore
 - docker-compose.yml
 - Dockerfile
 - Gemfile
 - Gemfile.lock
 - jekyll-serve.sh
 - LICENSE.txt
 - package.json
 - README.md
 - webpack.config.js
 - source
 - node_modules
 - terraform
