- title: Do the right thing.
  description: |
    You almost always know what's the right thing to do. It's the choice that is fair, ethical, and decent. It's the
    choice that lets you feel good as a human being. Always make that choice, even if it means losing a client or
    losing money. Be a good person.

- title: Take pride in your craft.
  description: |
    Whether you write code, make sales calls, or work on legal documents, do it well. You could call it "attention to
    detail," "great taste," "crafsmanship" or, as Michael Feather's puts it, "Clean code always looks like it was
    written by someone who cares." Whatever you call it, always strive to do work you can be proud of.

- title: Get things done.
  description: |
    The counterpart to pride in craftsmanship is finding a way to get things done. The most beautiful code that never
    ships or sits unfinished adds no value, no matter how beautifully it's crafted. Don't let perfect be the enemy of
    good.

- title: Incrementalism.
  description: |
    The best way to get things done is to do work incrementally. We believe that quanitity of iteration beats quality
    of iteration. Plan projects so that every increment is valuable by itself. Optimize for fast feedback rather than
    trying to come up with a perfect plan. Aim to recover quickly rather than trying to avoid all mistakes.
